# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('key_skills', models.TextField()),
                ('additional_skills', models.TextField()),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=16)),
                ('linkedin_profile', models.TextField()),
                ('github_projects', models.TextField()),
                ('slideshare_links', models.TextField()),
                ('youtube_links', models.TextField()),
                ('additional_details', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
